### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by ashvin-zwt** [zealousweb/accept-authorize-net-payments-using-contact-form-7#1]
Hello Team,
I'm using this plugin and found one issue related to the validation.
If I click on the submit button without any interaction on the form it will redirect to the payment form without checking the required field validation. After filling in the credit card information click on the submit button it will show the previous form error(One or more fields have an error. Please check and try again).

**Comment by Cristopher2511** [comment]
Hi @ashvin-zwt 

Thanks for adding issue in detail, We have solved the validation issue and remove Two step form which is brack CF7 validation flow. New version is  1.8. 

Thanks
